--- #YAML:1.0
name:                App-Module-Lister
version:             0.13
abstract:            List all of the installed modules with just Perl 5.6 code
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
